/* Edite textos, contatos, imagens e integrações somente aqui.
   Não habilite catálogo/avaliação estruturada sem confirmação do negócio.
   Imagens: {src, avif, webp, srcset, alt, width, height}. Caminhos relativos. */
window.CONTENT = {
  config: {siteUrl: 'https://gl-farias-estetica-automotiva.oaken-mochi-8060.chatgpt.site', ratingVerified: false, supabase: {url: '', anonKey: '', enabled: false}, analyticsEnabled: false},
  seo: {title:'GL Farias Estética Automotiva | Cuidado em Cubatão',description:'Cuidado automotivo em Cubatão. Conheça a GL Farias, veja os relatos dos clientes e converse com a equipe sobre o seu carro.',socialTitle:'GL Farias — Cuidado que aparece nos detalhes.',socialDescription:'Seu carro pode voltar a parecer novo. Estética automotiva em Cubatão.',image:'assets/images/social-preview.png'},
  brand: {name: 'GL Farias Estética Automotiva', short: 'GL FARIAS', descriptor: 'ESTÉTICA AUTOMOTIVA', tagline: 'Cuidado que aparece nos detalhes.', logo: ''},
  contact: {phone: '(13) 99731-4068', whatsapp: '5513997314068', instagram: 'gl.farias_esteticautomotiva', street: 'Rua Armando de Salles Oliveira, 530', district: 'Jardim São Francisco', city: 'Cubatão', state: 'SP', zip: '11500-010', hours: ['Segunda a sexta · 08:00 às 18:00', 'Sábado · 08:00 às 16:00'], mapEmbedUrl: ''},
  nav: [['servicos','Serviços'],['resultados','Resultados'],['processo','Processo'],['avaliacoes','Avaliações'],['faq','FAQ'],['contato','Contato']],
  ui: {skip: 'Ir para o conteúdo', menu: 'Abrir menu', close: 'Fechar', schedule: 'Agendar atendimento', primary: 'Quero cuidar do meu carro', results: 'Ver resultados', direct: 'Prefiro falar direto', next: 'Continuar para o WhatsApp', photo: 'Fotografia real em breve', before: 'Antes', after: 'Depois', slider: 'Arraste para comparar antes e depois', illustration: 'Demonstração visual ilustrativa. Fotografias reais serão adicionadas.', scroll: 'Explore o cuidado', privacy: 'Política de Privacidade', terms: 'Termos', navigation: 'Navegação', contact: 'Contato', attendance: 'Atendimento', home: 'Início', map: 'Abrir no mapa', instagram: 'Ver Instagram', footerCredit: 'Site por FDSS', rights: 'GL Farias Estética Automotiva.', details: 'Detalhe', google: 'Google', stars: '5 de 5 estrelas'},
  hero: {eyebrow: 'ESTÉTICA AUTOMOTIVA · CUBATÃO', lines: ['SEU CARRO','PODE VOLTAR A','PARECER NOVO.'], description: 'Estética automotiva com atenção aos detalhes, produtos profissionais e acabamento para quem não aceita qualquer cuidado com o próprio carro.', visualLabel: 'REFLEXO DO CUIDADO', caption: 'Cada detalhe importa.', image: null},
  rating: {value: '5,0', count: 8, label: 'NO GOOGLE', reviews: 'avaliações', note: 'Avaliações informadas para este site.'},
  authority: ['Produtos profissionais', 'Atendimento recomendado', 'Cubatão · SP'],
  problem: {eyebrow: '01 / UM NOVO OLHAR', title: 'Quando foi a última vez que você olhou para o seu carro e sentiu que ele estava impecável?', text: 'A rotina deixa marcas. A sujeira se acumula, o brilho perde espaço e o interior já não transmite a mesma sensação. Seu carro merece atenção de novo.', tags: ['Sujeira acumulada', 'Perda de brilho', 'Interior pedindo cuidado']},
  transformation: {eyebrow: '02 / A TRANSFORMAÇÃO', title: 'É a diferença entre limpar e cuidar.', text: 'Mais do que uma aparência limpa. A sensação de olhar de novo e perceber o cuidado.', stages: ['Sujo', 'Cuidado', 'Acabamento', 'Resultado'], beforeImage: null, afterImage: null},
  services: {eyebrow: '03 / O CUIDADO CERTO', title: 'Seu carro tem uma necessidade. O cuidado começa por ela.', items: [
    {id:'higienizacao', confirmed:false, title:'Interior limpo. Sensação de carro renovado.', label:'HIGIENIZAÇÃO COMPLETA', text:'A higienização completa aparece nos relatos de quem já passou por aqui. Converse com a equipe sobre disponibilidade e o cuidado indicado para o seu interior.', benefits:['Conte como está o interior','Explique o que gostaria de melhorar','Receba orientação da equipe'], cta:'Consultar higienização', image:null},
    {id:'externo', confirmed:false, title:'Um novo olhar para o exterior.', label:'LAVAGEM / CUIDADO EXTERNO', text:'O cuidado começa entendendo as condições do veículo. Consulte as opções de atendimento para o seu carro.', cta:'Conversar sobre meu carro', image:null}], other: [], prompt:'Seu carro precisa de qual cuidado?', known:'Sei o que preciso', recommendation:'Preciso de uma recomendação'},
  quality: {eyebrow:'04 / EM CADA DETALHE', title:'Qualidade aparece nos detalhes.', steps:[
    {title:'Produtos',text:'Produtos profissionais e de primeira linha: um cuidado reconhecido nos relatos dos clientes.',photo:'DETALHE DE PRODUTOS'},
    {title:'Cuidado',text:'Atenção ao que o seu carro precisa. Capricho que os clientes percebem e fazem questão de contar.',photo:'EQUIPE / AMBIENTE'},
    {title:'Acabamento',text:'O serviço termina nos detalhes. É ali que a aparência de bem cuidado faz a diferença.',photo:'DETALHE DE PINTURA'},
    {title:'Resultado',text:'“Impecável”, “parecia novo”. A percepção de quem entregou o carro e recebeu cuidado de volta.',photo:'RESULTADO FINAL'}]},
  process: {eyebrow:'05 / SIMPLES DESDE O INÍCIO',title:'Você entrega o carro. A gente cuida do resto.', steps:['Converse com a equipe','Informe o que seu carro precisa','Receba a orientação do serviço','Agende','Deixe o cuidado com a GL Farias']},
  why: {title:'Não é só o carro que recebe atenção.',text:'Atendimento próximo, cuidado no serviço e atenção aos detalhes.',aside:'E, segundo quem já passou por aqui, até o cafezinho merece elogio.',photo:'EQUIPE / AMBIENTE'},
  results: {eyebrow:'06 / O CUIDADO GANHA FORMA',title:'O resultado mora nos detalhes.',text:'Este espaço vai receber registros reais da GL Farias.',photos:[{label:'RESULTADO FINAL',image:null},{label:'DETALHE DE PINTURA',image:null}]},
  testimonials: {eyebrow:'07 / QUEM CONHECE, CONTA',title:'Quem entrega o carro, conta como recebeu de volta.',items:[
    {name:'Icaro Joda Ferlante',type:'Local Guide',text:'Qualidade pura... ainda mais se pedir higienização completa... produtos de qualidade.'},
    {name:'Kelly Olivr',text:'Quero deixar meu elogio ao Lava Rápido GL Farias Estética Automotiva. O atendimento foi ótimo e o carro ficou impecável, parecia novo. Dá pra ver o cuidado e capricho no serviço. Recomendo muito.'},
    {name:'Guilherme Laturdes',text:'Atendimento incrível, super atenciosos, profissionais de primeira! E o carro ficou 0km novamente! Recomendo demais!'},
    {name:'Sebastian Albuquerque',text:'Um ótimo serviço. Um dos melhores atendimentos. E um cafezinho excelente. Super indico.'},
    {name:'Joao Junior',type:'Local Guide',text:'Bom atendimento, profissional qualificado, produtos de 1ª linha. Super indico.'},
    {name:'Ricardo 013 Fernandes',type:'Local Guide',text:'Ótimo atendimento de recepção e serviços de qualidade. Equipe de parabéns. Super indico.'},
    {name:'M Q',text:'Atendimento ótimo. Recomendo.'},
    {name:'Fabio Luiz',text:'Serviços de alta qualidade e produtos profissionais.'}]},
  emotion: {words:['Limpo.','Impecável.','Parecendo novo.'],caption:'Palavras de quem já viveu esse cuidado.'},
  funnel: {eyebrow:'08 / AGORA É COM O SEU CARRO',title:'Conte o que ele precisa. A gente começa por aí.',text:'Algumas informações ajudam a equipe a orientar seu atendimento.'},
  cta: {title:'Se você cuida do seu carro, não entrega para qualquer um.',text:'Veja por que clientes da região destacam o atendimento, os produtos e o resultado da GL Farias.',button:'Quero agendar',micro:'Leva menos de 1 minuto para informar o que seu carro precisa.',image:null},
  form: {title:'Vamos cuidar do seu carro?',intro:'Conte um pouco sobre ele. A conversa continua no WhatsApp.',labels:['Qual seu nome?','Qual é o seu veículo?','O que você procura?','Como está o carro hoje?','Quando gostaria de fazer?','WhatsApp'],namePlaceholder:'Seu nome',vehiclePlaceholder:'Ex.: Honda Civic 2020',phonePlaceholder:'(13) 99999-9999',selectPlaceholder:'Selecione uma opção',services:['Higienização','Lavagem / cuidado','Estética completa','Ainda não sei','Outro'],conditions:['Precisa de uma limpeza','Está bem sujo','Quero recuperar a aparência','Quero manutenção periódica','Quero conversar com um profissional'],urgencies:['Hoje / o quanto antes','Nos próximos dias','Nesta semana','Estou pesquisando'],notice:'Ao continuar, seus dados serão usados para atender sua solicitação e compor a mensagem no WhatsApp.',success:'Sua mensagem está pronta. Continue no WhatsApp para enviar à equipe.',fallback:'Abrir minha mensagem no WhatsApp',phoneError:'Informe um telefone com DDD, de 10 ou 11 dígitos.',message:'Olá! Conheci a GL Farias pelo site.\n\nMeu nome é {name}.\n\nVeículo: {vehicle}\n\nEstou procurando: {service}\n\nSituação atual: {condition}\n\nGostaria de realizar: {urgency}\n\nQuero saber qual serviço vocês recomendam para o meu carro.',directMessage:'Olá! Conheci a GL Farias pelo site e gostaria de conversar sobre o cuidado do meu carro.'},
  faq: {eyebrow:'09 / SEM DÚVIDAS',title:'Antes de entregar as chaves.',items:[
    ['Preciso saber exatamente qual serviço contratar?','Não. Explique como está seu carro e o que você gostaria de melhorar. A equipe pode orientar sobre a opção mais adequada.'],
    ['Vocês fazem higienização completa?','Há relato de cliente citando higienização completa. Consulte a equipe para confirmar a disponibilidade e os detalhes do serviço.'],
    ['Quanto tempo o serviço demora?','O tempo depende do serviço e das condições do veículo. Entre em contato para confirmar.'],
    ['Preciso agendar?','Consulte a disponibilidade pelo WhatsApp para combinar seu atendimento.'],
    ['Quais produtos vocês utilizam?','A experiência de clientes menciona produtos profissionais e de primeira linha. Para informações sobre produtos específicos, consulte a equipe.'],
    ['Onde fica a GL Farias?','Rua Armando de Salles Oliveira, 530, Jardim São Francisco, Cubatão - SP.'],
    ['Como solicito um orçamento?','Utilize o formulário do site ou fale diretamente pelo WhatsApp.']]},
  location: {title:'Seu carro pode ser o próximo.',eyebrow:'10 / ENCONTRE A GL FARIAS',mapLabel:'Seu próximo cuidado está aqui.',directions:'Como chegar'},
  legal: {privacy:'Os dados do formulário são usados para preparar seu atendimento no WhatsApp. Quando a integração de atendimento estiver habilitada, poderão ser registrados para acompanhamento da solicitação. Este site não mantém seus dados pessoais no armazenamento do navegador. A conversa e o envio da mensagem acontecem no WhatsApp, sujeito às políticas da plataforma. Para solicitar informações ou exclusão de dados de atendimento, entre em contato pelo telefone exibido no site.',terms:'O conteúdo apresenta a GL Farias e relatos de clientes fornecidos para este site. Disponibilidade, serviços, valores e prazos devem ser confirmados com a equipe. Demonstrações visuais e espaços reservados para fotografias não representam resultados reais. O envio do formulário prepara uma conversa e não confirma um agendamento.'}
};
