const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'dist');fs.mkdirSync(out,{recursive:true});
for(const item of ['index.html','css','js','assets','robots.txt','sitemap.xml'])fs.cpSync(path.join(root,item),path.join(out,item),{recursive:true});
const vm=require('node:vm'),context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'js/content.js'),'utf8'),context);const content=context.window.CONTENT;
const origin=process.argv[2]||content.config.siteUrl;let html=fs.readFileSync(path.join(out,'index.html'),'utf8');const escape=s=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
html=html.replace(/<title>.*?<\/title>/,`<title>${escape(content.seo.title)}</title>`).replace(/(<meta name="description" content=")[^"]*/,`$1${escape(content.seo.description)}`).replace(/(<meta property="og:title" content=")[^"]*/,`$1${escape(content.seo.socialTitle)}`).replace(/(<meta property="og:description" content=")[^"]*/,`$1${escape(content.seo.socialDescription)}`);
if(origin){const url=new URL(origin);if(url.protocol!=='https:')throw Error('Use domínio HTTPS real');const base=url.origin;html=html.replace('</head>',`<link rel="canonical" href="${base}/"><meta property="og:url" content="${base}/"><meta property="og:image" content="${base}/${content.seo.image}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(content.seo.socialTitle)}"><meta name="twitter:description" content="${escape(content.seo.socialDescription)}"><meta name="twitter:image" content="${base}/${content.seo.image}"></head>`);fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${base}/</loc></url></urlset>`);}
fs.writeFileSync(path.join(out,'index.html'),html);
console.log('Build estático pronto em dist.');
