const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.QA_BROWSER || 'msedge'});const page=await browser.newPage();const errors=[];page.on('pageerror',err=>errors.push(err.message));
 await page.addInitScript(()=>{window.open=(url)=>{window.__opened=url;return null;};window.__events=[];addEventListener('gl:analytics',e=>window.__events.push(e.detail));});
 const results=[];
 for(const width of [320,360,375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:4173');await page.waitForSelector('h1');await page.waitForTimeout(1700);assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.review').count(),8);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`overflow ${width}`);results.push({width,overflow});}
 await page.screenshot({path:'qa-desktop.png',fullPage:false});
 await page.locator('[data-qualify="hero"]').click();await page.locator('[name=name]').fill('Teste QA');await page.locator('[name=vehicle]').fill('Veículo de teste');await page.locator('[name=service]').selectOption('Ainda não sei');await page.locator('[name=condition]').selectOption({index:1});await page.locator('[name=urgency]').selectOption({index:1});await page.locator('[name=phone]').fill('13999999999');await page.locator('.submit').click();assert.match(await page.evaluate(()=>window.__opened),/^https:\/\/wa.me\/5513997314068\?text=/);assert.match(decodeURIComponent(await page.evaluate(()=>window.__opened)),/Teste QA/);assert.equal(await page.locator('.form-status a').count(),1);assert.equal(await page.evaluate(()=>localStorage.length),0);await page.locator('[data-close]').click();
 await page.locator('#question-0').click();assert.equal(await page.locator('#question-0').getAttribute('aria-expanded'),'true');await page.locator('#answer-0').waitFor({state:'visible'});
 await page.locator('#comparison-range').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#comparison-range').inputValue(),'51');
 await page.evaluate(()=>{CONTENT.config.supabase={enabled:true,url:'https://supabase-test.invalid',anonKey:'test'};window.fetch=()=>Promise.reject(new Error('simulated offline'));});
 await page.locator('[data-qualify="recommendation"]').click();assert.equal(await page.locator('[name=service]').inputValue(),'Ainda não sei');await page.locator('[name=name]').fill('Fallback QA');await page.locator('[name=vehicle]').fill('Teste');await page.locator('[name=condition]').selectOption({index:1});await page.locator('[name=urgency]').selectOption({index:4});await page.locator('[name=phone]').fill('13999999999');await page.locator('.submit').click();assert.match(decodeURIComponent(await page.evaluate(()=>window.__opened)),/Fallback QA/);await page.locator('[data-close]').click();
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4173');await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.locator('#mobile-menu a[href="#servicos"]').click();assert.equal(await page.locator('#mobile-menu').isVisible(),false);assert.equal(await page.evaluate(()=>document.body.classList.contains('locked')),false);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'qa-mobile.png'});assert.equal(await page.locator('.pin-spacer').count(),0);
 const anchors=await page.evaluate(()=>[...document.querySelectorAll('a[href^="#"]')].filter(a=>!document.querySelector(a.getAttribute('href'))).length);assert.equal(anchors,0);assert.deepEqual(errors,[]);
 // Simulate a failed CDN: all essential interactions and content remain available.
 await page.route('https://cdn.jsdelivr.net/**',r=>r.abort());await page.goto('http://127.0.0.1:4173');assert.equal(await page.locator('.review').count(),8);await page.locator('[data-qualify="hero"]').click();assert.equal(await page.locator('#qualification').isVisible(),true);
 fs.writeFileSync('qa-results.json',JSON.stringify({results,checks:['8 reviews','form WhatsApp encoding','popup fallback','Supabase rejection fallback','keyboard comparison','FAQ','mobile menu and scroll unlock','reduced motion no pin','valid anchors','CDN failure fallback','no personal data in localStorage'],errors},null,2));await browser.close();console.log('QA passed');
})().catch(e=>{console.error(e);process.exit(1)});
